id: 67c79ed0009346b6b79fc2b4b52b4f1e
initial_creation_type: ocr
source_metadata:
  volumes:
    15f82135637d41f782f403dde6dba458:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: སྟོང་པ་ཉིད་བདུན་ཅུ་པའི་འགྲེལ་པ།
      total_pages: 1605
      volume_number: 57
